# app/utils/receipt_generator.py
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from io import BytesIO
from datetime import datetime

def generate_receipt_pdf(transaction, user):
    """
    transaction: ORM object (transaction)
    user: ORM object (user)
    returns bytes
    """
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 80, "TajiriCircle - Digital Receipt")

    c.setFont("Helvetica", 12)
    c.drawString(50, height - 120, f"User: {user.name or user.phone}")
    c.drawString(50, height - 140, f"Phone: {user.phone}")
    c.drawString(50, height - 160, f"Date: {transaction.timestamp.strftime('%Y-%m-%d %H:%M:%S')}")
    c.drawString(50, height - 180, f"Amount: {transaction.amount:.2f} {transaction.currency}")
    c.drawString(50, height - 200, f"Source: {transaction.source or 'N/A'}")
    c.drawString(50, height - 220, f"Type: {transaction.tx_type or 'N/A'}")
    c.drawString(50, height - 240, "Reference: autogenerated")

    c.line(50, height - 250, width - 50, height - 250)
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(50, height - 270, "This is an auto-generated receipt from TajiriCircle.")

    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer.read()
